apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: test-webhook
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple-ubuntu
  template:
    metadata:
      labels:
        app: simple-ubuntu
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        ports:
        - containerPort: 80
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 31; done;" ]

