apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple-ubuntu
  template:
    metadata:
      labels:
        app: simple-ubuntu
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        ports:
        - containerPort: 80
