apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-
  namespace: test-webhook
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: post-sync-job-container
        image: curlimages/curl
        command:
        - "curl"
        - "-X"
        - "POST"
        - "-d"
        - "'{\"message\":\"From the hook: {{ .app.status.sync.revision }}\"}'"
        - test-webhook.test-webhook.svc.cluster.local

